### ISSUE TITLE
add lit-html/element template

### ISSUE THREAD

**Issue by thepassle** [ndom91/create-pika-app#10]
It would be great to also have a lit-html/element starter, I have a similar setup [here](https://github.com/thepassle/reddit-pwa)

I'm working on a PR :)

**Comment by ndom91** [comment]
Good stuff! Cant wait to take a look!

**Comment by FredKSchott** [comment]
Woo! We have a few other examples in this doc that could probably be migrated pretty easily: https://github.com/pikapkg/web/blob/master/EXAMPLES.md

I'd love to get some package "init" examples in as well, for @pika/pack projects

**Comment by thepassle** [comment]
I based the app-lit setup on the vue setup, PR here https://github.com/pikapkg/init/pull/11

**Comment by ndom91** [comment]
@thepassle merged your PR. Can I close this?

**Comment by thepassle** [comment]
Just realised I forgot to version bump 😅 Could you bump the version and do a release?

**Comment by ndom91** [comment]
@thepassle yeah no worries. Thanks again!
