### ISSUE TITLE
Feature: Add initial question to differentiate pack or web -type projects 

### ISSUE THREAD

**Issue by ndom91** [ndom91/create-pika-app#12]
So if you do not specify a template and go through the flow of selecting one in the cli, we want to add a fork at the very beginning which would present two separate sets of templates depending on if you're building a library/package or a website/app. 

Specifically, this differentiates between @pika/pack and @pika/web based projects.

**Comment by FredKSchott** [comment]
@ndom91 what are your thoughts on this, post Snowpack rename? I'm fine to keep this Snowpack-specific going forward, and not try to also focus on the "package" creation flow.

**Comment by ndom91** [comment]
Yeah I think focusing on one thing and doing that well is a better way forward.
