### ISSUE TITLE
Bug: app-preact not working

### ISSUE THREAD

**Issue by drwpow** [ndom91/create-pika-app#19]
2 errors with trying to run this template with `npm run dev`:

**emotion**
The first error off the bat is with TypeScript:

```
node_modules/preact-emotion/types/preact.d.ts:15:37 - error TS2694: Namespace 'global.JSX' has no exported member 'IntrinsicElements'.

15   withComponent<T extends keyof JSX.IntrinsicElements>(
                                       ~~~~~~~~~~~~~~~~~
```

It doesn’t really help that [emotion has officially dropped support for Preact](https://github.com/emotion-js/emotion/pull/896). I think all the code for preact-emotion is for older versions of Emotion and Preact, but currently I don’t think the two work together (at least not in TypeScript land).

I got around this in my app by… well just using `postcss` and `postcss-preset-env`. Don’t really have a favorite CSS-in-JS solution for Preact currently 😕 

**preact-router**
I didn’t get past this step in this template, but for [my own app](https://github.com/dangodev/pika-web-preact) I had to shim @pika/web to fix a problem with `preact-router`. Would welcome thoughts [on this PR](https://github.com/pikapkg/web/pull/101).

**Comment by ndom91** [comment]
@dangodev good catch. I removed `preact-emotion` for now and its running again, but would like to add another CSS-in-JS library to replace it. 

How are you liking `postcss` and `postcss-preset-env`?

**Comment by drwpow** [comment]
I’d say Preset Env ([website](https://preset-env.cssdb.org/)) is almost a replacement for Sass, but much more standards-compliant and easier to set up in a pipeline. It’s basically Babel for CSS, but there are other PostCSS plugins that can do some powerful things. Overall it’s so standard it’s not really controversial/opinionated. Most devs may need something more (BEM, Tailwind CSS, Bulma, etc.).

But CSS-in-JS it’s not. Unfortunately I’m not sure where the Preact community is in terms of what they’re using there.

**Comment by drwpow** [comment]
You may also find success with [Preact compat](https://preactjs.com/guide/v10/switching-to-preact/#setting-up-compat) in setting up Styled Components or Emotion again (pretending that you’re using React). That’s something I haven’t tried.

**Comment by FredKSchott** [comment]
1 vote for https://github.com/lukejacksonn/csz, may be what you're looking for /w zero build tools

**Comment by ndom91** [comment]
Just tested it and the current `master` version of the `app-preact` template works for me on linux. @dangodev or @FredKSchott do you still want to make any changes regarding styling libraries? Or should I close this issue?

**Comment by drwpow** [comment]
Cool. Not regarding styling libraries; I’m good as long as we just fixed the type errors and simplified the config a bit (w/o Babel)

>

**Comment by drwpow** [comment]
Sorry; I was unclear. I’m +1 for closing the issue! I think it’s looking great. But I’m also +1 I think having a csz example would be cool too, whether that’s just the standard Preact flavor, or making `preact-postcss` and `preact-csz` variants, or whatever. But that can be another ticket down the line.

**Comment by ndom91** [comment]
Okay I'll close this one then and open another one regarding styling :thumbsup:
