### ISSUE TITLE
pika-init bin is outdated on npm

### ISSUE THREAD

**Issue by ricardomatias** [ndom91/create-pika-app#34]
I tried to install the Typescript template, but it didn't work due to missing files. The version of the binary is `1.1.2`. The --help command also is different than on the readme:

```cli
❯ pika-init --help
Usage: pika-init --template [template] <project-name>

Options:
  -V, --version              output the version number
  -t, --template [template]  template choice (optional)
  -h, --help                 output usage information

Examples: 
  $ pika-init --template app-preact my-new-app 
  $ pika-init my-new-app 

    If you have any problems, do not hesitate to file an issue:
      https://github.com/pikapkg/init/issues/new
```

After cloning and installing it locally, the bin looks and fails the same way.

**Comment by ndom91** [comment]
@ricardomatias can you please elaborate? How does it fail?

I believe the version currently on npm does in fact have a "typo" in its `config.json`, its fixed in `master` on here though (c6575553f133d469943a3a969e47b3def6bcb0b6).

the typescript example just built fine for me however.

**Comment by luciorubeens** [comment]
@ndom91 Same here, the typescript template does not exist in npm: https://unpkg.com/browse/snowpack-init@3.0.1/assets/

**Comment by ndom91** [comment]
@FredKSchott when you have some time, could you please push the current master to npm? Thanks!

**Comment by FredKSchott** [comment]
Done!
