### ISSUE TITLE
Archive repo

### ISSUE THREAD

**Issue by FredKSchott** [ndom91/create-pika-app#40]
This repo is no longer relevant for Snowpack v2. @ndom91 would you like to take back ownership of the repo? Otherwise, I'll archive it.

**Comment by ndom91** [comment]
All good, you can give it back to me if you want

**Comment by FredKSchott** [comment]
Great, I just added you with admin permissions, it's not currently possible for me to transfer to you, but you should now be able to transfer it to yourself here: https://github.com/pikapkg/snowpack-v1-init/settings

Thanks again for starting this project, and all of your work on it!
