### ISSUE TITLE
Allow user to choose from multiple templates

### ISSUE THREAD

**Issue by ndom91** [ndom91/create-pika-app#5]
## Status 

Currently @FredKSchott has created the structure to allow for multiple templates. 

Each template belongs in its own subdirectory under `assets/` (see `app-preact`). The template then requires a `config.json` file with any details that are required for this template, such as npm scripts, and most importantly, install commands so that the `create-pika-app` wrapper can install and prepare the project for the user. 

## Todo

- ~~Allow the user to select a template~~ e37730098cfd0d5dca26d44d1f6729109ef71be9
	When they are executing `create-pika-app` with only the project name, we could show a cli select menu  where it asks the user which available template they'd like to use. I think it makes sense to offer the template selection as a cli argument as well so that you can run this without any further user input. We could list the available template options either in `--help` and/or in the README. 

- **Integrate packages from Pika CDN?**
	So im not positive how possible this would even be, but what if you could pass a pika cdn URL as the template argument and it would prepare that project for you? Would this be helpful? How much easier would this be than simply `npm install https://cdn.pika.dev/package` ?

  Can we deliver any value on top of installing the package via this wrapper? 

- **Integrate more templates** :)

**Comment by ndom91** [comment]
@FredKSchott - I made an issue out of this so we can continue the discussion here.

**Comment by ndom91** [comment]
@thiagoabreu I noticed you have a Vue `@pikapkg/web` example project listed on their `examples.md` page. Do you mind if I use that project here as a second template to test selection, etc.?

**Comment by thiagojedi** [comment]
> @thiagoabreu I noticed you have a Vue `@pikapkg/web` example project listed on their `examples.md` page. Do you mind if I use that project here as a second template to test selection, etc.?

No problem. :+1:

**Comment by ndom91** [comment]
@thiagoabreu updated and integrated now :)

**Comment by FredKSchott** [comment]
@ndom91 We now have preact & vue, safe to close?

**Comment by thepassle** [comment]
Can we add a lit-html/lit-element template, too? I got a similar, but more minimal, setup [here](https://github.com/thepassle/reddit-pwa)

**Comment by ndom91** [comment]
> @ndom91 We now have preact & vue, safe to close?

Yeah lets close this one. If people want to add more, they can open a new issue specific to their template. 

@thepassle - can you please open a new issue regarding your lit-element template?

thanks!
